```{r}
library(ChIPseeker)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(org.Hs.eg.db)
```



```{r}
input_dir <- "../data/experiment1/peaks/"
output_dir <- "../results/"

bed_files <- c(
  "../data/experiment1/seacr_cpm/aFLAG_FIX_R1.seacr.peaks.stringent.bed",
  "../data/experiment1/seacr_cpm/aFLAG_NATIVE_R2.seacr.peaks.stringent.bed",
  "../data/experiment1/seacr_cpm/aFOXP3_NATIVE_R1.seacr.peaks.stringent.bed",
  "../data/experiment1/seacr_cpm/aFLAG_FIX_R2.seacr.peaks.stringent.bed",
  "../data/experiment1/seacr_cpm/aFOXP3_FIX_R1.seacr.peaks.stringent.bed",
  "../data/experiment1/seacr_cpm/aFOXP3_NATIVE_R2.seacr.peaks.stringent.bed",
  "../data/experiment1/seacr_cpm/aFLAG_NATIVE_R1.seacr.peaks.stringent.bed",
  "../data/experiment1/seacr_cpm/aFOXP3_FIX_R2.seacr.peaks.stringent.bed",
  "../data/experiment1/seacr_cpm/aH3K4me3_NATIVE_R1.seacr.peaks.stringent.bed"
)
bed_files2 <- c(
  "../data/experiment1/macs2_peaks/aFLAG_FIX_R1.macs2_summits.bed",
  "../data/experiment1/macs2_peaks/aFLAG_NATIVE_R2.macs2_summits.bed",
  "../data/experiment1/macs2_peaks/aFOXP3_NATIVE_R1.macs2_summits.bed",
  "../data/experiment1/macs2_peaks/aFLAG_FIX_R2.macs2_summits.bed",
  "../data/experiment1/macs2_peaks/aFOXP3_FIX_R1.macs2_summits.bed",
  "../data/experiment1/macs2_peaks/aFOXP3_NATIVE_R2.macs2_summits.bed",
  "../data/experiment1/macs2_peaks/aFLAG_NATIVE_R1.macs2_summits.bed",
  "../data/experiment1/macs2_peaks/aFOXP3_FIX_R2.macs2_summits.bed",
  "../data/experiment1/macs2_peaks/aH3K4me3_NATIVE_R1.macs2_summits.bed"
)


for (bed_file in bed_files) {
  
  base_name <- tools::file_path_sans_ext(basename(bed_file))
  output_file <- paste0(output_dir, base_name, "_genes.txt")
  
  peaks <- readPeakFile(bed_file)
  
  annotated_peaks <- annotatePeak(peaks, 
                                TxDb = TxDb.Hsapiens.UCSC.hg38.knownGene,
                                annoDb = "org.Hs.eg.db")
  
  gene_df <- as.data.frame(annotated_peaks)
  gene_list <- unique(gene_df$SYMBOL[!is.na(gene_df$SYMBOL)])
  
  write.table(gene_list, 
             file = output_file,
             col.names = FALSE, 
             row.names = FALSE, 
             quote = FALSE)
}
```


```{r}
annotated_peaks_df <- as.data.frame(annotated_peaks)
annotated_peaks_df
```


```{r}
gene_files <- c(
  # FLAG antibody - FIXED condition
  "../results/macs2/aFLAG_FIX_R1.macs2_summits_genes.txt",
  "../results/macs2/aFLAG_FIX_R2.macs2_summits_genes.txt",
  
  # FLAG antibody - NATIVE condition
  "../results/macs2/aFLAG_NATIVE_R1.macs2_summits_genes.txt",
  "../results/macs2/aFLAG_NATIVE_R2.macs2_summits_genes.txt",
  
  # FOXP3 antibody - FIXED condition
  "../results/macs2/aFOXP3_FIX_R1.macs2_summits_genes.txt",
  "../results/macs2/aFOXP3_FIX_R2.macs2_summits_genes.txt",
  
  # FOXP3 antibody - NATIVE condition
  "../results/macs2/aFOXP3_NATIVE_R1.macs2_summits_genes.txt",
  "../results/macs2/aFOXP3_NATIVE_R2.macs2_summits_genes.txt",
  
  # H3K4me3 antibody - NATIVE condition (only one replicate)
  "../results/macs2/aH3K4me3_NATIVE_R1.macs2_summits_genes.txt"
)


A <- readLines(gene_files[7])
B <- readLines(gene_files[8])

C <- intersect(A,B)

print(length(A))
print(length(B))
print(length(C))
```




